### ISSUE TITLE
Particle App does not recognize devices with Android v 6.0.1

### ISSUE THREAD

**Issue by danieldmarks** [spark/photon-tinker-android#7]
The Photon in my kit has not worked correctly. My friend, who has a lot of experience with these tried to help me but he believes there is something wrong with the Photon as well. You can see his posts on your support site.https://community.particle.io/t/photon-continually-blinking-blue-a-couple-things-to-eliminate/22317/11
I tried connecting with the USB cable and command line steps but it did not work either, similar to the other user on the forum.
I got a new Photon and it couldn't connect with my Android. I have two Particle accounts and it wouldn't see it on either one. Rather than try the USB interface again, I took it to my friend's office to see what he could do with it. He was able to log in with both Photons on his own account using an iPhone 6s and latest operating system. After reflashing the original Photon he was also able to use the iPhone to connect both Photons on my account. I was not able to connect either Photon on either of my Particle accounts using my Android device. It can see it on the WiFi but not on the app. 
I am using a Samsung Galaxy S7 (model SM-930V) Android version 6.0.1, Kernel version 3.18.20 and Particle app version 4.2.
Out of curiosity I then used the Particle app on my Samsung Note4 running Android version 5.1.1 and it recognized both of them. I reflashed both of them and they worked. Then I used the Particle app on the Galaxy S7 and this time both units could be seen and controlled by the tinker app!
I have no idea why this happened. Apparently the Photon doesn't like Android 6.0.1, at least to install the app but okay with running it.

**Comment by jensck** [comment]
Very odd; thanks for the bug report!

I'll get my hands on a Samsung device and try this out.

**Comment by bloukingfisher** [comment]
I've read the friends post and I have a Samsung Galaxy S6 with Android 6.0.1. I get stuck at the same point with a new Photon when the wifi "smart network switch" is enabled. When I disable it I can easily setup and claim a new Photon as I did today. I can't say this is exactly the problem but maybe @danieldmarks can replicate or test if this creates and solves the problem (wifi - advanced settings menu in Android). 

If that is the case, perhaps instead of a bug it should be a feature type request that the Particle Tinker app doesn't just 'hang' at that point but at minimum return with a helpful error message to direct someone to turn off the smart network switch. And better, with a tap of a button take them to that settings menu.
